### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by christianfong**
Adds a buildignore and actually makes the package compile.

### CODE REVIEW

**Comment by kosukeimai** [comment]
It looks like there is a bug in man/npCBPS.Rd  and DESCRIPTION: we have a travis ci checking to make sure that a new version passes R cran check

**Comment by christianfong** [comment]
Not disagreeing with you, but where do you see this?  I'm having trouble 
finding it.

**Comment by kosukeimai** [comment]
Do you see the travis link above?  If you click [Details](https://travis-ci.org/kosukeimai/CBPS/builds/173710760), then you will see a bunch of warnings.  travis ci automatically do the cran check, which is useful.

**Comment by kosukeimai** [comment]
There still is a problem.  Here is an error message:

npCBPS

  Code: function(formula, data, na.action, corprior = 0.01, print.level

```
             = 0, ...)
```

  Docs: function(formula, data, na.action, corprior = 0.1, print.level

```
             = 0, ...)
```

  Mismatches in argument default values:

```
Name: 'corprior' Code: 0.01 Docs: 0.1
```

checking for hidden files and directories ... NOTE

Kosuke Imai
Professor, Department of Politics
Center for Statistics and Machine Learning
Princeton University
http://imai.princeton.edu

**Comment by christianfong** [comment]
Yep, don't worry.  I understand how the system works now and will 
resolve all of the errors.  This one in particular has already been 
resolved.

**Pull request merged**
