### PR TITLE
ATT for hdCBPS

### PR DESCRIPTION
**Pull request by psdsam**
Adding ATT into hdCBPS

### CODE REVIEW

**Comment by christianfong** [comment]
I'm out of the loop on what's going on here.  What does this function do, and why should we put it in the CBIV branch if its modifying CBPSBinary?

**Comment by ratkovic** [comment]
Christian

Cleaned this up--moving from master to a branch.

Variance for CBPS binary.

Marc

---------------------------------------------------------------------------------
Marc Ratkovic
Assistant Professor
Department of Politics          Office: Corwin Hall 035
Princeton University             Email: ratkovic@princeton.edu
Princeton, NJ 08544-1012    http://www.princeton.edu/~ratkovic
---------------------------------------------------------------------------------
________________________________

**Comment by kosukeimai** [comment]
@ratkovic I think it would be helpful if you could explain to @christianfong exactly what you've done and update the documentation too.  Thanks.

**Comment by kosukeimai** [comment]
Also, @christianfong This merge is requested by @psdsam who wants to add high dimensional CBPS to the `cbiv` branch, which for whatever reason contains the initial changes regarding hdCBPS.  It should have been a separate branch but oh well...

**Comment by christianfong** [comment]
@ratkovic : I have several proposed changes to the binary variance function.  I will send details to you via email.

@psdsam: You can put your changes in CBIV if you want (especially since it doesn't affect the CBIV files), but I see that there is a request to merge CBIV into master.  CBIV is not ready to merge into master, and will not be ready for some time.  If you want to merge and submit to CRAN ahead of CBIV, you will need your own branch.

**Pull request closed without merging**
