### PR TITLE
Accuracy depends on long.double setting in R

### PR DESCRIPTION
**Pull request by HJ08003**
Adjust accuracy based on capabilities("long.double") status.

### CODE REVIEW

**Comment by HJ08003** [comment]
(1) On Mac, passed "R CMD check --as-cran" 
(2) On Window, passed "R CMD check --as-cran"
(3) Passed travis-ci check
(4) Passed win-builder
(5) On ubuntu with --disable-long-double, passed "R CMD check --as-cran"

**Comment by kosukeimai** [comment]
@HJ08003 Do you need to check each system?  Can you just use that one line without checking the system?

**Comment by HJ08003** [comment]
I don't know the long-double settings on those Solaris machines.  So I think it is better to keep them there.

Thanks

Hubert


On Feb 8, 2018 6:29 PM, Kosuke Imai <notifications@github.com> wrote:

@HJ08003<https://github.com/hj08003> Do you need to check each system? Can you just use that one line without checking the system?

**Comment by christianfong** [comment]
Hubert, I have a couple questions before we resubmit on Thursday.  I am worried that if we fail these checks again, Ripley will kick us off CRAN for good, so I think it is really important that we get them right.  Two things:

1) Do we now understand why the last solution we tried didn't work?
2) Are we totally sure that we will pass this time?  In particular, were you able to mirror Ripley's setup, replicate the error, and find that it passed?

**Comment by HJ08003** [comment]
1.  Do we now understand why the last solution we tried didn't work?
  2.  Are we totally sure that we will pass this time? In particular, were you able to mirror Ripley's setup, replicate the error, and find that it passed?

The last solution checks if a machine is Solaris or SunOS. If it is, the accuracy is set to be 0.005. That was based on the previous error that shown on a Sun Solaris machine. With that fix, CBPS should be OK on that Solaris machine.

But this time, it was on a machine we don’t know what that is. The only hint Kosuke found out was that it could be the long-double in computing that made the difference.  Thus, I compiled and installed R from source on a newly built Ubuntu machine, with long-double disabled. Then I cloned the CBPS package there (from my Github), ran the test and got the same errors. With the revision that checks for long-double flag and makes adjustment accordingly, the error is gone.

Based on that we are able to reproduce the exact same error from Ripley and the numbers matched exactly  as the following shows, I believe we emulated Ripley’s machine and the package should pass.

Do you want me to run the A-B test on the version you plan to submit ?

Thanks,

-Hubert




This is from Prof Ripley’s email
================================================================================================================
'machine-specific tolerance levels' are not allowed under the CRAN policy, so should not have been used.  Nor do I believe that errors like

  ── 1. Failure: tests CBMS on the Lalonde data (@test-all.R#36) ────────────────
  x["age", "age"] not equal to 0.01208261.
  1/1 mismatches
  [1] 0.00852 - 0.0121 == -0.00356

  ── 2. Failure: tests CBMS on the Lalonde data (@test-all.R#37) ────────────────
  x["re74", "re75"] not equal to -0.0311205.
  1/1 mismatches
  [1] 0.0058 - -0.0311 == 0.0369

can plausibly be attributed to tolerances.  'x' is a covariance matrix, which with long doubles is (to 3 digits)
==================================================================================================================



And here is what I did and the result I got:
==================================================================================================================
(1) Setup the A-B comparison

# Get from Github
cd A
git clone https://github.com/HJ08003/CBPS

# Get from Github
cd B
git clone https://github.com/HJ08003/CBPS

# Then I edited B/test/testthat/test-all.R, the only difference:
$ diff A/CBPS/tests/testthat/test-all.R B/CBPS/tests/testthat/test-all.R
19c19
< accuracy <- ifelse(capabilities("long.double"), accuracy, 0.05)
---
> # accuracy <- ifelse(capabilities("long.double"), accuracy, 0.05)

(2) Build the package and check --as-cran
R CMD build CBPS
R CMD check --as-cran

From A:
=======
* checking tests ...
  Running ‘testthat.R’
 OK
* checking PDF version of manual ... OK
* DONE

From B:
=======
* checking tests ...
  Running ‘testthat.R’
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  1/1 mismatches
  [1] 0.00852 - 0.0121 == -0.00356

  ── 2. Failure: tests CBMS on the Lalonde data (@test-all.R#38)  ────────────────
  x["re74", "re75"] not equal to -0.0311205.
  1/1 mismatches
  [1] 0.0058 - -0.0311 == 0.0369

  ══ testthat results  ═══════════════════════════════════════════════════════════
  OK: 8 SKIPPED: 0 FAILED: 2
  1. Failure: tests CBMS on the Lalonde data (@test-all.R#37)
  2. Failure: tests CBMS on the Lalonde data (@test-all.R#38)

  Error: testthat unit tests failed
  Execution halted
* checking PDF version of manual ... OK
* DONE

**Comment by HJ08003** [comment]
I did more tests on the Ubuntu machine. This time the CBPS package is cloned from Kosuke’s Github. Instead of commenting out that line, I deleted it in the comparison.

The same result is observed.

Thanks,

-Hubert

  255  cd C
  256  git clone https://github.com/kosukeimai/CBPS
  257  cd ../D
  258  git clone https://github.com/kosukeimai/CBPS
  259  vi CBPS/tests/testthat/test-all.R

$ diff C/CBPS/tests/testthat/test-all.R D/CBPS/tests/testthat/test-all.R
19d18
< accuracy <- ifelse(capabilities("long.double"), accuracy, 0.05)

(C)
  Running ‘testthat.R’
 OK
* checking PDF version of manual ... OK
* DONE

(D)
* checking tests ...
  Running ‘testthat.R’
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  1/1 mismatches
  [1] 0.00852 - 0.0121 == -0.00356

  ── 2. Failure: tests CBMS on the Lalonde data (@test-all.R#37)  ────────────────
  x["re74", "re75"] not equal to -0.0311205.
  1/1 mismatches
  [1] 0.0058 - -0.0311 == 0.0369

  ══ testthat results  ═══════════════════════════════════════════════════════════
  OK: 8 SKIPPED: 0 FAILED: 2
  1. Failure: tests CBMS on the Lalonde data (@test-all.R#36)
  2. Failure: tests CBMS on the Lalonde data (@test-all.R#37)

  Error: testthat unit tests failed
  Execution halted
* checking PDF version of manual ... OK
* DONE


From: Hubert Jin <hubertj@exchange.Princeton.EDU<mailto:hubertj@exchange.Princeton.EDU>>
Date: Tuesday, February 27, 2018 at 2:47 PM
To: kosukeimai/CBPS <reply@reply.github.com<mailto:reply@reply.github.com>>, kosukeimai/CBPS <CBPS@noreply.github.com<mailto:CBPS@noreply.github.com>>
Cc: Hubert Jin <hubertj@exchange.Princeton.EDU<mailto:hubertj@exchange.Princeton.EDU>>, Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: Re: [kosukeimai/CBPS] Accuracy depends on long.double setting in R (#14)


  1.  Do we now understand why the last solution we tried didn't work?
  2.  Are we totally sure that we will pass this time? In particular, were you able to mirror Ripley's setup, replicate the error, and find that it passed?

The last solution checks if a machine is Solaris or SunOS. If it is, the accuracy is set to be 0.005. That was based on the previous error that shown on a Sun Solaris machine. With that fix, CBPS should be OK on that Solaris machine.

But this time, it was on a machine we don’t know what that is. The only hint Kosuke found out was that it could be the long-double in computing that made the difference.  Thus, I compiled and installed R from source on a newly built Ubuntu machine, with long-double disabled. Then I cloned the CBPS package there (from my Github), ran the test and got the same errors. With the revision that checks for long-double flag and makes adjustment accordingly, the error is gone.

Based on that we are able to reproduce the exact same error from Ripley and the numbers matched exactly  as the following shows, I believe we emulated Ripley’s machine and the package should pass.

Do you want me to run the A-B test on the version you plan to submit ?

Thanks,

-Hubert




This is from Prof Ripley’s email
================================================================================================================
'machine-specific tolerance levels' are not allowed under the CRAN policy, so should not have been used.  Nor do I believe that errors like

  ── 1. Failure: tests CBMS on the Lalonde data (@test-all.R#36) ────────────────
  x["age", "age"] not equal to 0.01208261.
  1/1 mismatches
  [1] 0.00852 - 0.0121 == -0.00356

  ── 2. Failure: tests CBMS on the Lalonde data (@test-all.R#37) ────────────────
  x["re74", "re75"] not equal to -0.0311205.
  1/1 mismatches
  [1] 0.0058 - -0.0311 == 0.0369

can plausibly be attributed to tolerances.  'x' is a covariance matrix, which with long doubles is (to 3 digits)
==================================================================================================================



And here is what I did and the result I got:
==================================================================================================================
(1) Setup the A-B comparison

# Get from Github
cd A
git clone https://github.com/HJ08003/CBPS

# Get from Github
cd B
git clone https://github.com/HJ08003/CBPS

# Then I edited B/test/testthat/test-all.R, the only difference:
$ diff A/CBPS/tests/testthat/test-all.R B/CBPS/tests/testthat/test-all.R
19c19
< accuracy <- ifelse(capabilities("long.double"), accuracy, 0.05)
---
> # accuracy <- ifelse(capabilities("long.double"), accuracy, 0.05)

(2) Build the package and check --as-cran
R CMD build CBPS
R CMD check --as-cran

From A:
=======
* checking tests ...
  Running ‘testthat.R’
 OK
* checking PDF version of manual ... OK
* DONE

From B:
=======
* checking tests ...
  Running ‘testthat.R’
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  1/1 mismatches
  [1] 0.00852 - 0.0121 == -0.00356

  ── 2. Failure: tests CBMS on the Lalonde data (@test-all.R#38)  ────────────────
  x["re74", "re75"] not equal to -0.0311205.
  1/1 mismatches
  [1] 0.0058 - -0.0311 == 0.0369

  ══ testthat results  ═══════════════════════════════════════════════════════════
  OK: 8 SKIPPED: 0 FAILED: 2
  1. Failure: tests CBMS on the Lalonde data (@test-all.R#37)
  2. Failure: tests CBMS on the Lalonde data (@test-all.R#38)

  Error: testthat unit tests failed
  Execution halted
* checking PDF version of manual ... OK
* DONE

**Comment by christianfong** [comment]
Thanks, Hubert.  So what happened is that our last update fixed the issue on Solaris, but then Ripley went out and found a new issue (presumably to make his point that we were not to use machine checks)?  

This all seems very thorough to me, so I am quite happy.  Sorry to bother you.  Just wanted to be as sure as possible that we had all our ducks in a row.

**Comment by HJ08003** [comment]
I think the Solaris result was from the CRAN check which has a list of platforms for the package to be tested.
Thanks,
-Hubert

**Pull request merged**
