### PR TITLE
high-dimensional CBPS

### PR DESCRIPTION
**Pull request by kosukeimai**
@christianfong Can you see if this looks good to you?  Thanks.  @psdsam created a branch from the `cbiv` branch and so I'm requesting a merge into that branch rather than the `master` branch

### CODE REVIEW

**Comment by kosukeimai** [comment]
@psdsam There is one more `Note` concerning your change (see [this](https://travis-ci.org/kosukeimai/CBPS/builds/225998368)).  Would you mind fixing it?  Thanks.

**Comment by psdsam** [comment]
Hi Kosuke,

I see. My code requires the package glmnet. I am not sure where to include
the package in this process though. Do you have any idea?

Thank you,

Best,

Sida

**Comment by kosukeimai** [comment]
Try adding the package to `DESCRIPTION` file and also import the functions you are using in `NAMESPACE`

**Comment by psdsam** [comment]
I think it has been fixed.

**Pull request merged**
